### ISSUE TITLE
Remove active border on menu

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc.github.io#163]
The menu button looks quite strange while being in the active state:

![Bildschirmfoto 2021-09-10 um 22 50 29](https://user-images.githubusercontent.com/3978662/132916373-cff65d65-1979-43fe-a5af-692d8f8e5a71.png)

**Comment by ccoenen** [comment]
If this is part of the `:focus` style, I would advise to not *completely* remove it. `:focus` is important for keyboard navigation and removing it hinders accessibility.

**Comment by mrdrogdrog** [comment]
It's because of `:focus`. Therefore: No. Don't remove it.

**Comment by DerMolly** [comment]
Then this should be closed
