### ISSUE TITLE
Authenticate ownership with links

### ISSUE THREAD

**Issue by SISheogorath** [hedgedoc/hedgedoc.github.io#22]
We could consider to add `rel="me"` to some of the menu and footer links.

For example the link on Mastodon could verified for the account, if the link would be available with `rel="me"` attribute (and use the direct instance URL instead of `social.hedgedoc.org`)

**Comment by DerMolly** [comment]
is it enough to put that in the header with `<link rel='me' src='mastodon-link'>`?

**Comment by ErikMichelson** [comment]
I just tested it out. Adding a `<link>` in header is enough for mastodon. I'm on it.
