### ISSUE TITLE
History page: s/aboutt/about/

### ISSUE THREAD

**Issue by inducer** [hedgedoc/hedgedoc.github.io#28]
https://hedgedoc.org/history/

**Comment by DerMolly** [comment]
do you mean this? I could not find anywhere else with aboutt
![image](https://user-images.githubusercontent.com/3978662/99649291-5238b680-2a54-11eb-99b9-98d503644a28.png)

**Comment by inducer** [comment]
Renders like this for me:

![grafik](https://user-images.githubusercontent.com/352067/99676456-23afe100-2a3e-11eb-9174-09377f7b6c11.png)

**Comment by ErikMichelson** [comment]
Weird, the svg source code has the correct space between the words.

**Comment by inducer** [comment]
Firefox 83.0 on Debian Linux.

**Comment by mrdrogdrog** [comment]
This problem will be solved with the improved version of the history page

**Comment by DerMolly** [comment]
This should be fixed with the history overhaul. Therefore I'll close this now. Thanks for the issue and feel free to open new issues if you find anything else.
