### ISSUE TITLE
Add releases

### ISSUE THREAD

**Issue by SISheogorath** [hedgedoc/hedgedoc.github.io#44]
We should find a way to provide releases and/or release notes on our website.

We can probably utilise the GitHub API to get the name of the release as well as a link to the release notes.

This could help people to find them without being "GitHub aware".

**Comment by mrdrogdrog** [comment]
Which advantage do we have if we recreate the github release page on our website?
IMHO we can get the same effect if we redirect the user to https://github.com/hedgedoc/hedgedoc/releases

**Comment by mrdrogdrog** [comment]
Okay new idea: instead of recreating the release listing from github we create ONE page for the newest stable release.
With some text, download button, link to the docker image and the documentation and the github release page for the other releases and and... 
This would be a lot more useful.@DerMolly what do you think?

**Comment by DerMolly** [comment]
I think if one wants to update from x to y and x is not newest release - 1. This makes the page more useless / frustrating than helpfull

**Comment by mrdrogdrog** [comment]
Yes but then the person can visit the github release page. Download pages on project homepages are for new people.

**Comment by mrdrogdrog** [comment]
Also we don't have upgrade paths

**Comment by DerMolly** [comment]
I'm not to sure I like the idea of getting the release on the homepage in the homepages design. With spoiler tags to show only the names and maybe have the last entry open by default…

**Comment by SISheogorath** [comment]
My idea was to display it in a similar fashion as GitHub does it on the repository page. Some very basic information (name, version, release date) and a link to the releases on GitHub. Nothing special there. Maybe also a link to the upgrade instructions and breaking changes we should start to maintain better.
