### ISSUE TITLE
Add docker image tag to releases page

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/hedgedoc.github.io#56]
The new releases (and download) page does contain a hint about our docker image. The section currently only includes a link to quay.io. I'd like to see the corresponding docker image tag directly on the releases page.

For accomplishing that we either need to push pre-1.6 versions to hedgedoc/hedgedoc as well or differentiate in our hugo template whether codimd/server or hedgedoc/hedgedoc needs to be used.

Optionally we also could [the quay.io-API](https://docs.quay.io/api/swagger/) to check whether the image tag exists.

**Comment by DerMolly** [comment]
I'd suggest keeping hedgedoc/hedgedoc clean of pre1.6.0 releases and request the quay.io api to check the new and old registry.
