### ISSUE TITLE
Release Page: Always show release notes

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc.github.io#59]
Currently, the release notes are hidden behind a details-click-thingy. As the release notes often contain important information about upgrading, they should not be hidden by default.
We already had a few support cases where people missed the note about `X-Forwarded-Proto` headers in the release notes.

**Comment by ErikMichelson** [comment]
To be clear, this only is related to the release notes on the specific release page and not on the overview. Am I right?
