### ISSUE TITLE
Link to /releases

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc.github.io#90]
As I just (re)discovered it's currently not possible to click you way from the homepage to <https://hedgedoc.org/releases/>, which I think should be changed.

**Comment by ErikMichelson** [comment]
I thought it was intentional that people first had to visit the page of the newest release in order to get to the list of older releases. This could assure that people don't install older versions (e.g. CodiMD ones because the name sounds more familiar to them).

**Comment by DerMolly** [comment]
Can one get to the /latest-release page? If so I didn't find it

**Comment by ErikMichelson** [comment]
Click "Download"

**Comment by DerMolly** [comment]
Then this can be closed and I order myself glasses…
